substitutions: 
  ap_password: "123456789"
  ota_password: "123456789"

esphome:
  name: monoledcontroller
  friendly_name: Monochromatic Led Controller
  name_add_mac_suffix: True
  project:
    name: MorganMLGman.MonochromaticLedController
    version: 1.0.0

esp8266:
  board: esp01_1m
  restore_from_flash: true
  early_pin_init: false
  framework:
    version: recommended

packages: 
  esp01_1m_remote:
    url: https://github.com/MorganMLGman/ESPHomeBaseFiles
    files:
      - ESP8266/esp01_1m.yaml
    ref: master
    refresh: 1d

ota:
  - platform: esphome
    id: ota_esphome
    password: ${ota_password}

output:
  - platform: esp8266_pwm
    pin: 
      number: GPIO3
      inverted: true
    frequency: 1000 Hz
    id: pwm_output
    min_power: 0.15
    zero_means_zero: true

light:
  - platform: monochromatic
    name: LED Chain
    id: led_chain
    output: pwm_output
    restore_mode: RESTORE_DEFAULT_OFF 

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      inverted: true
      mode:
        input: true
        pullup: true
    name: Button
    filters:
      - delayed_on_off: 20ms
    on_click:
      - min_length: 50ms
        max_length: 500ms
        then: 
          - light.toggle: led_chain

      - min_length: 10s
        max_length: 30s
        then: 
          - button.press: factory_reset_button